# Generated by Django 6.0.3 on 2026-04-01 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('telefone', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('num_pessoas', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='Pendente', max_length=20)),
                ('criado_em', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
