# Generated by Django 6.0.3 on 2026-04-06 18:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestauranteAPOLLO', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='Número da Mesa')),
                ('capacidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidade máxima')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['numero'],
            },
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-data', 'horario'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='nome_cliente',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='telefone',
        ),
        migrations.AddField(
            model_name='reserva',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data',
            field=models.DateField(verbose_name='Data da Reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horario',
            field=models.TimeField(verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='num_pessoas',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de Pessoas'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RestauranteAPOLLO.mesa', verbose_name='Mesa Atribuída'),
        ),
    ]
